### ISSUE TITLE
Pick V0

### ISSUE THREAD

**Issue by awunderground** [awunderground/math658_project#1]

**Comment by bbontempo3** [comment]
In the table at the bottom of page 8, I tried calculating a couple of the priority values, and for some reason the last five digits did not match up with the values recorded in the table. Do you think that this is simply due to some type of rounding error?

I checked the first few “marginal variance” values, and it looks like R is doing exactly what the algorithm is supposed to be doing. The only thing for us to note is that even though there are “n = 100” rows in the table, the overall sample size (i.e., the “n” referred to in Algorithm IV) that corresponds to this table is actually n = 100 + 4 = 104, since the initial allocation is (1, 1, 1, 1). I checked this by adding up the cumulative “n_h” values from the table.

**Comment by bbontempo3** [comment]
On page 11, if “qnorm(0.95)” refers to the z-value for a 90% confidence interval, then shouldn’t this value be squared (see the formula for n)?

**Comment by bbontempo3** [comment]
For a desired bound V_0, should we simply use something like V_0 = 0.1*statistic – i.e., we don’t want V(y_bar_str) to be any greater than 10% of the stratified sample mean (the weighted average of the four stratum sample means)  calculated from the pilot sample, and we don’t want V(p_hat_str) to be any greater than 10% of the stratified sample proportion assumed for the pilot sample (10% of 0.5 in this case)?

**Comment by awunderground** [comment]
```
I checked the first few “marginal variance” values, and it looks like R is doing exactly what the algorithm is supposed to be doing. The only thing for us to note is that even though there are “n = 100” rows in the table, the overall sample size (i.e., the “n” referred to in Algorithm IV) that corresponds to this table is actually n = 100 + 4 = 104, since the initial allocation is (1, 1, 1, 1). I checked this by adding up the cumulative “n_h” values from the table.
```

Exactly! `n` corresponds to number of observations from each strata including the initial (1, 1, 1, 1)

**Comment by bbontempo3** [comment]
Ok, then maybe you could add a "^2" to the qnorm(0.95) term in the code on page 11.

**Comment by awunderground** [comment]
I added it to both calculations. 

I think the difference in priority values could be because of rounding. The numbers are massive and squares and cubes can have some imprecision. I don't think it matters much.

**Comment by awunderground** [comment]
Ok, so, V0 = (0.1 * 535087.4)^2 for mean price. 

How about V0 = 0.1^2 for the proportion?

**Comment by bbontempo3** [comment]
Sure, 0.1^2 sounds fine to me. I guess our choices for V_0 will end up being somewhat arbitrary.

**Comment by bbontempo3** [comment]
On page 13, where you calculate “strata_variance,” shouldn’t this expression match the summand of the very first sum in the decomposition of V(p_hat_str) on page 12 – i.e., [(N_h^2)*(N_h – 1)*(0.25)] / [(N^2)*(N_h – 1)]?

**Comment by bbontempo3** [comment]
So that for the starting variance, we can just sum these from h =1 to 4 (as you did for y_bar_str)?

**Comment by awunderground** [comment]
Ok, I added the remaining 2 conditions. I think we need to relax condition 2 or adjust our adjust our calculations to get `property_value`.
